export const PLATFORMS = [
  {
    name: "Github",
    logo: "/icons/icon-github-gray.svg",
    color: "#010409",
    text: "#FFFFFF",
    url: "https://github.com/",
  },
  {
    name: "Frontend Mentor",
    logo: "/icons/icon-frontend-mentor.svg",
    color: "#FFFFFF",
    text: "#000000",
    url: "https://www.frontendmentor.io/profile/",
  },
  {
    name: "Twitter",
    logo: "/icons/icon-twitter.svg",
    color: "#000000",
    text: "#FFFFFF",
    url: "https://twitter.com/",
  },
  {
    name: "LinkedIn",
    logo: "/icons/icon-linkedin.svg",
    color: "#2d68ff",
    text: "#FFFFFF",
    url: "https://www.linkedin.com/in/",
  },
  {
    name: "YouTube",
    logo: "/icons/icon-youtube.svg",
    color: "#ff0000",
    text: "#FFFFFF",
    url: "https://www.youtube.com/channel/",
  },
  {
    name: "Facebook",
    logo: "/icons/icon-facebook.svg",
    color: "#2442ac",
    text: "#FFFFFF",
    url: "https://www.facebook.com/",
  },
  {
    name: "Twitch",
    logo: "/icons/icon-twitch.svg",
    color: "#9146ff",
    text: "#FFFFFF",
    url: "https://www.twitch.tv/",
  },
  {
    name: "Dev.to",
    logo: "/icons/icon-devto.svg",
    color: "#333333",
    text: "#FFFFFF",
    url: "https://dev.to/",
  },
  {
    name: "Codewars",
    logo: "/icons/icon-codewars.svg",
    color: "#8a1a50",
    text: "#FFFFFF",
    url: "https://www.codewars.com/users/",
  },
  {
    name: "Codepen",
    logo: "/icons/icon-codepen.svg",
    color: "#1e1f26",
    text: "#FFFFFF",
    url: "https://codepen.io/",
  },
  {
    name: "freeCodeCamp",
    logo: "/icons/icon-freecodecamp.svg",
    color: "#302267",
    text: "#FFFFFF",
    url: "https://www.freecodecamp.org/",
  },
  {
    name: "GitLab",
    logo: "/icons/icon-gitlab.svg",
    color: "#eb4925",
    text: "#FFFFFF",
    url: "https://gitlab.com/",
  },
  {
    name: "Hashnode",
    logo: "/icons/icon-hashnode.svg",
    color: "#0330d1",
    text: "#FFFFFF",
    url: "https://hashnode.com/@",
  },
  {
    name: "Stack Overflow",
    logo: "/icons/icon-stack-overflow.svg",
    color: "#ec7100",
    text: "#FFFFFF",
    url: "https://stackoverflow.com/users/",
  },
] as const

export type Platform = (typeof PLATFORMS)[number]
